misconfigurations:
  # Instance does not require IMDS access to require a token - https://avd.aquasec.com/misconfig/aws/ec2/avd-aws-0028/
  - id: AVD-AWS-0028
    paths:
      - cloudformation/EC2InstanceWithDockerSample.yaml
  # Security group rule allows ingress from public internet - https://avd.aquasec.com/misconfig/aws/ec2/avd-aws-0107/
  - id: AVD-AWS-0107
    paths:
      - cloudformation/EC2InstanceWithDockerSample.yaml
  # Subnet associates public IP address - https://avd.aquasec.com/misconfig/avd-aws-0164
  - id: AVD-AWS-0164
    paths:
      - cloudformation/EC2InstanceWithDockerSample.yaml
