name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: megalinter/megalinter@v6.14.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          DISABLE_LINTERS: SPELL_CSPELL
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          SPELL_CSPELL_FILTER_REGEX_INCLUDE: README.md
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
