name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions: read-all

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: MegaLinter
        uses: megalinter/megalinter@v7.0.2
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          DISABLE_LINTERS: REPOSITORY_KICS,SPELL_CSPELL
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          SPELL_CSPELL_FILTER_REGEX_INCLUDE: README.md
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
